branch-defaults:
  master:
    environment: weblocks-env
    group_suffix: null
global:
  application_name: weblocks
  branch: null
  default_ec2_keyname: lance-test
  default_platform: Node.js
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
deploy:
  artifact: source.zip
